version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:19"
      timezone: "Etc/UTC"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:19"
      timezone: "Etc/UTC"
