[tox]
envlist = lint-check,py{310,311,312,313,314}-{minimum,current}
skipsdist = True

[testenv]
setenv =
    SOURCES = pycaw/ tests/ examples/
deps = minimum: -r{toxinidir}/requirements.txt
       current: comtypes
       current: psutil
       -r{toxinidir}/test-requirements.txt
commands = pytest --cov=pycaw --cov-report term --cov-report xml tests/

[coverage:run]
relative_files = True

[testenv:coveralls]
passenv = GITHUB_*
setenv =
    COVERALLS_SERVICE_NAME = github
commands = coveralls

[testenv:lint-check]
commands =
    ruff check {env:SOURCES}
    ruff format --check {env:SOURCES}

[testenv:lint-format]
commands =
    ruff check --fix {env:SOURCES}
    ruff format {env:SOURCES}
